[package]
name = "bam"
version = "0.0.1"
authors = ["Timofey Prodanov <timofey.prodanov@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
libflate = "0.1.27"
crc = "1.8.1"
lru-cache = "0.1.2"

[dev-dependencies]
rand = "0.7.0"

[profile.test]
opt-level = 3