[package]
name = "bam"
version = "0.0.1"
authors = ["Timofey Prodanov <timofey.prodanov@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 3
debug = true

[profile.test]
opt-level = 3

[features]
default = []
check_crc = ["crc"]

[dependencies]
byteorder = "1.3"
libflate = "0.1.27"
lru-cache = "0.1.2"
crc = { version = "1.8.1", optional = true }

[dev-dependencies]
rand = "0.7.0"
